### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by wulei** [mingjunyang/atom-format-lua#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-format-lua](https://github.com/mingjunyang/atom-format-lua) package, v0.0.5

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1119

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1119:26)
  at Object.exports.spawn (child_process.js:977:9)
  at Object.module.exports.AtomFormatLua.format (/Users/Leo/.atom/packages/atom-format-lua/lib/atom-format-lua.coffee:54:24)
  at atom-workspace.subscriptions.add.atom.commands.add.atom-format-lua:format (/Users/Leo/.atom/packages/atom-format-lua/lib/atom-format-lua.coffee:12:94)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -9:43.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -9:42.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:33.8.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -6:03.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -5:58.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:58.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:58.4.0 atom-beautify:beautify-editor (atom-text-editor.editor.vim-mode.insert-mode)
     -5:51.7.0 core:copy (atom-notification.warning.icon.icon-alert.native-key-bindings.has-detail.has-close)
     -1:51.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 atom-format-lua:format (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.12
atom-ctags, v4.2.0
atom-format-lua, v0.0.5
autocomplete-paths, v1.0.2
file-icons, v1.6.9
highlight-selected, v0.10.1
language-lua, v0.9.4
language-protobuf, v0.5.0
linter, v1.5.1
linter-jshint, v1.2.0
linter-lua, v1.0.0
monokai, v0.18.0
symbols-tree-view, v0.10.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by mingjunyang** [comment]
@wulei  亲，非常抱歉的告诉你，从一开始我就是在linux下测试的，就连windows下也是有问题的。我木有mac os来运行和测试代码，我们需要等待好心人来帮助我们。
我觉得你可以解决这个问题的，atom的Packages写起来真的好简单好简单的。我就看了一下文档，借用了另一个项目，在linux下就能运行了。
在 luacode 文件夹下面的formatter.lua 可以在lua5.1下手工执行.....

**Comment by dieterplex** [comment]
In my case(10.11.2), `lua51path=process.spawnSync('which', ['lua5.1'])` won't get any result 

quick workaround, fallback lua51 after catch block in `lib/atom-format-lua.coffee`
```coffeescript 
        if not lua51
          lua51 = "/usr/local/bin/lua"
```
If you brew install lua51, replace lua51 with `lua: "/usr/local/bin/lua5.1"`
