### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by mzgs** [mingjunyang/atom-format-lua#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-format-lua](https://github.com/mingjunyang/atom-format-lua) package, v0.1.1

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at format (/Users/mustafa/.atom/packages/atom-format-lua/lib/atom-format-lua.js:69:20)
    at atom-workspace.atomFormatLuaFormat (/Users/mustafa/.atom/packages/atom-format-lua/lib/atom-format-lua.js:14:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.4.0 atom-format-lua:format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "atom-format-lua": {
    "lua51": "/Users/mustafa/lua-5.3.2"
  }
}
```

### Installed Packages

```coffee
# User
atom-format-lua, v0.1.1
autocomplete-corona, v1.0.2
color-picker, v2.1.1
file-icons, v1.6.17
highlight-selected, v0.11.2
language-lua, v0.9.4
minimap, v4.19.0
open-recent, v5.0.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by mingjunyang** [comment]
@mzgs  try lua 5.1.x, not support lua 5.3.

**Comment by mzgs** [comment]
i used lua 5.1 still same error

**Comment by mingjunyang** [comment]
@mzgs   Maybe is privilege took this problem.

**Comment by ryanplusplus** [comment]
@mzgs I think this is because you provided the directory that the Lua binary is in. You need to give the full path to the executable. Try:

```lua
{
  "core": {},
  "atom-format-lua": {
    "lua51": "/Users/mustafa/lua-5.3.2/lua"
  }
}
```

**Comment by Sakhi29** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
OsirisXTLS, @leolianger, @cluc-dev, @rcbarnes, @MarsCoder, @dedecn, @crazyguitar, @sergio-hilgert, @JT5D, @galacticinquisitor, @lajarre, @cristiandouce, @ZeroD-inc, @BlinkVoid, @lauralee00, @ZackChang007, @jfc221, @gergannap, @siculars, @BBlooms

**Comment by rapkaan** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
VisionAries77, @bulleric, @alexchamberlain, @devchafa, @shx9asd22, @jellea, @leokofi, @onurmatik, @rg7822, @Kolajy, @tudisco, @abkoyuncu, @jambillking, @moonhillwealth, @SaysZEN, @vincentqiu, @Matt-Zhang, @thecao365, @CendyBY, @birdming22
